### PR TITLE
add possibility to modify collapse, in and collapsing default classes

### PR DESCRIPTION
**Pull request by borya09**

### CODE REVIEW

**Comment by onokumus** [comment]
@borya09 
Why would users need this? They would have to change a metisMenu.css too

**Comment by borya09** [comment]
In my case, I use my own css styles, with a BEM syntax, so I would like to name things in a different way.
On the other hand, the same problem is produced with the 'active' class. If a user changes the name of this class, the metisMenu.css has also to be changed.

**Comment by borya09** [comment]
thanks!

**Comment by onokumus** [comment]
@borya09 
Your welcome.

**Pull request merged**
